language: node_js
node_js:
  - "6"

before_install:
  # Clone the repository if isn't cloned
  - "mkdir node_modules"
  - "git clone git@github.com:ianpaschal/aurora.git node_modules/aurora"
  - "cd node_modules/aurora"
  # Reset the repo so we can have a conflict-less pull
  - "git reset --hard"
  - "git clean -f"
  - "git pull"
  # Install dependencies
  - "npm install"
  - "cd .."

install:
  - npm install

script:
  - npm run lint
  - npm run pack:prod
